### Register a test user
POST http://localhost:5000/api/account/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "test123",
  "is_teacher": 0
}


### Login
POST http://localhost:5000/api/account/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "test123"
}


### GET current session user info
GET http://localhost:5000/api/account/me

### Create a class
POST http://localhost:5000/api/class/create
Content-Type: application/json

{
  "class_name": "Test Class",
  "subject": "Science",
  "daily_point_cap": 10
}
### GET CLASS INFO (basic info)
GET http://localhost:5000/api/class/1

### GET CLASS MEMBERS (with active rewards)
GET http://localhost:5000/api/class/1/members


### GET CLASS QUIZZES
GET http://localhost:5000/api/class/1/quizzes

### GET CLASS MEMBERS (with active rewards)
GET http://localhost:5000/api/class/1/members

### GET class overview for logged-in user
GET http://localhost:5000/api/class/overview