### Register a test user
POST http://localhost:5000/api/account/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "test123",
  "is_teacher": 0
}


### Login
POST http://localhost:5000/api/account/login
Content-Type: application/json

{
  "username": "adam1",
  "password": "adam123"
}


### GET current session user info
GET http://localhost:5000/api/account/me

### Create a class
POST http://localhost:5000/api/class/create
Content-Type: application/json

{
  "class_name": "Test Class",
  "subject": "Science",
  "daily_point_cap": 10
}
### GET CLASS INFO (basic info)
GET http://localhost:5000/api/class/1

### GET CLASS MEMBERS (with active rewards)
GET http://localhost:5000/api/class/1/members


### GET CLASS QUIZZES
GET http://localhost:5000/api/class/1/quizzes

### GET CLASS MEMBERS (with active rewards)
GET http://localhost:5000/api/class/1/members

### GET class overview for logged-in user
GET http://localhost:5000/api/class/overview

### POST submit quiz answers
POST http://localhost:5000/api/quiz/user-answers
Content-Type: application/json

{
  "quiz_id": 2,
  "answers": [
    { "answer_id": 1 },
    { "answer_id": 2 },
    { "answer_id": 3 }
  ]
}

### POST award points

POST http://localhost:5000/api/quiz/award-points
Content-Type: application/json

{
  "points_delta": 30,
  "description": "Completed Sample Quiz",
  "quiz_id": 2
}